# Generated by Django 2.1.5 on 2019-06-02 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('blue_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('orange_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('overtime', models.BooleanField(default=False)),
                ('overtime_length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_goal', models.IntegerField()),
                ('game', models.ForeignKey(on_delete='CASCADE', to='rocketleague.Game')),
            ],
        ),
    ]
