# Generated by Django 2.2.1 on 2019-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190524_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='note',
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
